name: Deploy Website

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to SmarterASP.NET

    # Deployment runs only when 'it is manual run' or the commit message contains "[deploy]"
    if: >
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.head_commit.message, '[deploy]')

    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Deploy website
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

          local-dir: ./
          server-dir: ${{ secrets.FTP_SITE_DIRECTORY }}

          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/node_modules/**
            README.md
